name: Staged deployments
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: 'environment'
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "Building...."
      
  Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Test
    steps:
      - run: echo "Deployed to test!"
      
  Production:
    runs-on: ubuntu-latest
    needs: Test
    environment: prod
    steps:
      - run: echo "Production 🚀"
